name: Super-Linter

on:
  push:
    paths-ignore:
      - 'plugins/**'
      - 'world/**'
      - 'logs/**'
      - 'cache/**'
      - 'crash-reports/**'
      - 'paper-**/**'
      - 'help/**'
      - 'data/**'
      - 'libraries/**'
      - 'versions/**'

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        run: rm -rf ${{ runner.workspace }}/node_modules/.cache/super-linter

      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Super-Linter
        uses: github/super-linter@v4.10.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
